AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: A rideshare price tracking service for Uber and Lyft

Resources:
  compare:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Timeout: 10
      Events:
        compare:
          Type: Api
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          UBER_API_KEY:
          LYFT_API_KEY:
